# Generated by Django 5.0.3 on 2024-03-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('portfolio_link', models.URLField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_time', models.CharField(choices=[('express', 'Express 24hrs'), ('up_3_days', 'Up to 3 days'), ('up_7_days', 'Up to 7 days'), ('anytime', 'Anytime')], max_length=20)),
                ('located', models.CharField(choices=[('us_only', 'US Only'), ('worldwide', 'Worldwide')], max_length=20)),
                ('type_fl', models.CharField(choices=[('graphic_designer', 'Graphic Designer'), ('front_end_developer', 'Front-End Developer'), ('back_end_developer', 'Back-End Developer'), ('full_stack_developer', 'Full Stack Developer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('logo_design', 'Logo Design'), ('web_ui_design', 'Web U/I Design'), ('mobile_ui_design', 'Mobile U/I Design'), ('illustration', 'Illustration'), ('email_design', 'Email Design'), ('infographics_design', 'Infographics Design'), ('branding_and_identity_design', 'Branding and Identity Design'), ('front_end_development', 'Front-End Development'), ('back_end_development', 'Back-End Development'), ('full_stack_development', 'Full-Stack Development'), ('e_commerce_development', 'E-Commerce Development'), ('web_application_development', 'Web Application Development'), ('responsive_web_design', 'Responsive Web Design'), ('search_engine_optimization', 'Search Engine Optimization (SEO)'), ('social_media_marketing', 'Social Media Marketing'), ('pay_per_click_advertising', 'Pay-Per-Click (PPC) Advertising'), ('content_marketing', 'Content Marketing'), ('email_marketing', 'Email Marketing'), ('influencer_marketing', 'Influencer Marketing'), ('online_reputation_management', 'Online Reputation Management'), ('ios_app_development', 'iOS App Development'), ('andriod_app_development', 'Android App Development'), ('cross_platform_app_development', 'Android App Development'), ('mobile_game_development', 'Mobile Game Development'), ('app_testing_and_quality_assurance', 'App Testing and Quality Assurance'), ('app_maintenance_and_updates', 'App Maintenance and Updates'), ('network_security', 'Network Security'), ('ethical_hacking', 'Ethical Hacking'), ('penetration_testing', 'Penetration Testing'), ('security_auditing', 'Security Auditing'), ('data_encription', 'Data Encryption'), ('incident_response', 'Incident Response'), ('security_compliance', 'Security Compliance')], default='logo_design', max_length=33)),
                ('location', models.CharField(choices=[('united_states', 'United States'), ('worldwide', 'Worldwide')], default='united_states', max_length=16)),
                ('timeframe', models.CharField(choices=[('1to3months', '1 - 3 Months'), ('3to6months', '3 - 6 Months'), ('morethan6months', 'More than 6 months')], default='logo_design', max_length=24)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='main_app.freelancerprofile')),
            ],
        ),
    ]
