# Generated by Django 4.2.11 on 2024-03-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprofile_client_user_freelancer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='client',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='freelancer',
        ),
    ]
