# Generated by Django 5.0.3 on 2024-03-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_client_lasname_remove_client_name_and_more'),
        ('main_app', '0002_userprofile_client_user_freelancer_user'),
    ]

    operations = [
    ]
