# Generated by Django 5.0.3 on 2024-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_jobposting_client_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='delivery',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='located',
            field=models.CharField(choices=[('USA', 'Worldwide')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
