# Generated by Django 4.2.11 on 2024-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_jobposting_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='timeframe',
            field=models.CharField(choices=[('1to3months', '1 - 3 Months'), ('3to6months', '3 - 6 Months'), ('morethan6months', 'More than 6 months')], default='logo_design', max_length=24),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('logo_design', 'Logo Design'), ('web_ui_design', 'Web U/I Design'), ('mobile_ui_design', 'Mobile U/I Design'), ('illustration', 'Illustration'), ('email_design', 'Email Design'), ('infographics_design', 'Infographics Design'), ('branding_and_identity_design', 'Branding and Identity Design'), ('front_end_development', 'Front-End Development'), ('back_end_development', 'Back-End Development'), ('full_stack_development', 'Full-Stack Development'), ('e_commerce_development', 'E-Commerce Development'), ('web_application_development', 'Web Application Development'), ('responsive_web_design', 'Responsive Web Design'), ('search_engine_optimization', 'Search Engine Optimization (SEO)'), ('social_media_marketing', 'Social Media Marketing'), ('pay_per_click_advertising', 'Pay-Per-Click (PPC) Advertising'), ('content_marketing', 'Content Marketing'), ('email_marketing', 'Email Marketing'), ('influencer_marketing', 'Influencer Marketing'), ('online_reputation_management', 'Online Reputation Management'), ('ios_app_development', 'iOS App Development'), ('andriod_app_development', 'Android App Development'), ('cross_platform_app_development', 'Android App Development'), ('mobile_game_development', 'Mobile Game Development'), ('app_testing_and_quality_assurance', 'App Testing and Quality Assurance'), ('app_maintenance_and_updates', 'App Maintenance and Updates'), ('network_security', 'Network Security'), ('ethical_hacking', 'Ethical Hacking'), ('penetration_testing', 'Penetration Testing'), ('security_auditing', 'Security Auditing'), ('data_encription', 'Data Encryption'), ('incident_response', 'Incident Response'), ('security_compliance', 'Security Compliance')], default='logo_design', max_length=33),
        ),
    ]
