# Generated by Django 5.0.3 on 2024-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_delivery_freelancerprofile_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='delivery_time',
            field=models.CharField(choices=[('express', 'Express 24hrs'), ('up_3_days', 'Up to 3 days'), ('up_7_days', 'Up to 7 days'), ('anytime', 'Anytime')], max_length=20),
        ),
    ]
